### ISSUE TITLE
Signup endpoint returns server error on post

### ISSUE THREAD

**Issue by ranilwallace** [getlendme/backend#8]
Data submitted to the signup route returns "Server Error" on submission:

<img width="499" alt="Screen Shot 2021-02-02 at 1 57 44 PM" src="https://user-images.githubusercontent.com/12215778/106649253-4d69a600-655f-11eb-8cd6-47a8048ef787.png">

This is after submitting data with content-type being form-data and x-www-form-urlencoded.

While testing, I realize that if I remove one of the required fields, validation errors are returned:

<img width="556" alt="Screen Shot 2021-02-02 at 2 00 27 PM" src="https://user-images.githubusercontent.com/12215778/106649504-ad604c80-655f-11eb-9da1-118461dfbfc6.png">

In addition, the route listed [here](https://dev.getlendme.com/api/documentation) in the documentation for signup is incorrect. It should be `/v1/auth/signup` and not`/user/v1/auth/signup`

**Comment by antony2kx** [comment]
The issue has been resolved.
